catalogue_path <- file.path("inst", "discovery", "workflows.yml")
catalogue <- yaml::read_yaml(catalogue_path)
workflows <- catalogue$workflows

format_list <- function(x) {
  if (length(x) == 0) {
    return("None specified")
  }

  paste(x, collapse = ", ")
}

article <- c(
  "---",
  'title: "Find the right vivainsights function"',
  'description: "Choose package functions by analytical task instead of writing custom analysis code."',
  "---",
  "",
  "<!-- Generated by tools/generate-discovery.R; do not edit manually. -->",
  "",
  "# Find the right function",
  "",
  "Start with the task below before writing custom `dplyr`, `ggplot2`, or network code.",
  "The package functions apply established Viva Insights aggregation and privacy conventions.",
  "",
  "| Task | Start with | Input | Returns | Python parity |",
  "|---|---|---|---|---|"
)

for (workflow in workflows) {
  python_name <- if (is.null(workflow$python_function)) {
    workflow$parity
  } else {
    paste0("`", workflow$python_function, "()` (", workflow$parity, ")")
  }

  article <- c(
    article,
    paste0(
      "| ", workflow$task,
      " | `", workflow$r_function, "()`",
      " | ", workflow$input_grain,
      " | ", workflow$returns,
      " | ", python_name, " |"
    )
  )
}

article <- c(
  article,
  "",
  "## Workflow details",
  ""
)

for (workflow in workflows) {
  article <- c(
    article,
    paste0("### ", workflow$task),
    "",
    paste0(
      "**Use:** [`", workflow$r_function, "()`](",
      workflow$documentation,
      ")"
    ),
    "",
    paste0("**Typical requests:** ", format_list(workflow$intents)),
    "",
    paste0("**Required columns:** ", format_list(workflow$required_columns)),
    "",
    paste0("**Privacy:** ", workflow$privacy),
    "",
    paste0("**Returns:** ", workflow$returns),
    "",
    "```r",
    workflow$example,
    "```",
    "",
    paste0(
      "**Related functions:** ",
      paste0("`", workflow$related, "()`", collapse = ", ")
    ),
    ""
  )
}

if (tail(article, 1) == "") {
  article <- head(article, -1)
}

writeLines(article, file.path("vignettes", "function-discovery.Rmd"))

llms <- c(
  "# vivainsights",
  "",
  "> R package for analyzing and visualizing Microsoft Viva Insights data.",
  "",
  "Use an existing vivainsights function before writing custom aggregation or visualization code.",
  "Most grouped functions expose `mingroup`; preserve this privacy threshold unless the user explicitly chooses another valid threshold.",
  "",
  "## Primary workflows",
  ""
)

for (workflow in workflows) {
  llms <- c(
    llms,
    paste0(
      "- ", workflow$task, ": `", workflow$r_function, "()`; ",
      "input: ", workflow$input_grain, "; ",
      "returns: ", workflow$returns, "; ",
      "privacy: ", workflow$privacy, "; ",
      "docs: ", workflow$documentation
    )
  )
}

llms <- c(
  llms,
  "",
  "## Documentation",
  "",
  "- Task guide: https://microsoft.github.io/vivainsights/articles/function-discovery.html",
  "- Function reference: https://microsoft.github.io/vivainsights/reference/index.html",
  "- Analyst guide: https://microsoft.github.io/vivainsights/analyst_guide_intro.html",
  paste0(
    "- Python parity baseline: vivainsights ",
    catalogue$python$version,
    " at commit ",
    catalogue$python$commit
  )
)

writeLines(llms, file.path("inst", "discovery", "llms.txt"))
